#!/usr/bin/env bash
# This is the for loop syntax in bash scripting.

# shellcheck disable=SC2034 #i is unused variable

for i in {1..10}; do
	echo "Best School"
done

# Another solution is to use C-style syntax, which will use the i variable;
# for (( i = 1; i <= 10; i++ )); do
# 	echo "BestSchoo2"
# done


