#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.

IFS=":"

while read -r username _ userid _ _ homedir _; do
	echo "$username:$userid:$homedir"
done < /etc/passwd
